//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sazay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _context;


        public Entities()
            : base("name=Entities")
        {
        }
        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disciplini> Disciplini { get; set; }
        public virtual DbSet<Ekzamen> Ekzamen { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Prepodavateli> Prepodavateli { get; set; }
        public virtual DbSet<Studenti> Studenti { get; set; }
        public virtual DbSet<Uchebnii_plan> Uchebnii_plan { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
