//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sazay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepodavateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prepodavateli()
        {
            this.Uchebnii_plan = new HashSet<Uchebnii_plan>();
        }
    
        public int Tab_nomer { get; set; }
        public string Familia { get; set; }
        public string Im9 { get; set; }
        public string Otchestvo { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uchebnii_plan> Uchebnii_plan { get; set; }
    }
}
