//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sazay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studenti()
        {
            this.Ekzamen = new HashSet<Ekzamen>();
        }
    
        public int N_zach_knigi { get; set; }
        public int N_group { get; set; }
        public string Familia { get; set; }
        public string Im9 { get; set; }
        public string Otchestvo { get; set; }
        public string Specialnost { get; set; }
        public string Otdelenie { get; set; }
        public Nullable<int> ID_group { get; set; }
        public int ID { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ekzamen> Ekzamen { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
